[build-system]
requires = ["setuptools>=51.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = [
    "--cov=modbus_proxy",
    "--cov-report=html", "--cov-report=term",
    "--durations=2", "--verbose"
]
testpaths = ["tests"]