[build-system]
requires = ["setuptools>=51.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = [
    "--cov=modbus_proxy",
    "--cov-report=html", "--cov-report=term",
    "--durations=5", "--verbose"
]
testpaths = ["tests"]

[tool.black]
# just signal the project uses black for editors like emacs python-black
